"""Update employee table

Revision ID: 12d7570faa93
Revises: bc163e9d5965
Create Date: 2026-07-02 09:30:22.437107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d7570faa93'
down_revision: Union[str, Sequence[str], None] = 'bc163e9d5965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_code', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=False))
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('employees_user_id_key'), 'employees', type_='unique')
    op.create_unique_constraint(None, 'employees', ['employee_code'])
    op.drop_column('employees', 'leave_balance')
    op.drop_column('employees', 'joining_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('leave_balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_user_id_key'), 'employees', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'employee_code')
    # ### end Alembic commands ###
